version: '3'
services:
  rdatascience:
    image: joundso/rdsc_rstudio_j:latest
    restart: unless-stopped
    ports:
    - "8787:8787" #rstudio
    - "3838:3838" #shiny
    - "54321:54321" #h2o flow
    # https://github.com/rocker-org/rocker-versioned/blob/master/user/README.md
    environment:
    - DISPLAY=$IP:0
    volumes:
    ## work:
    # - ../docker-share/R:/home/user/share
    # - ../../../git-local:/home/user/git-local
    # - ../../../_p21/:/home/user/p21
    ## home:
    - /k/Docker/docker-share/R:/home/user/share
    - /d/git-local:/home/user/git-local
    tty: true
